name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_macos:
    name: Build for MacOS X
    runs-on: macos-latest
    steps:
      - name: Install system packages
        run: |
          brew install pkg-config opencl-icd-loader opencl-headers opencl-clhpp-headers sfml glm glew glfw
      - name: Setup pkg config path
        run: |
          export PKG_CONFIG_PATH="/usr/local/opt/opencl-icd-loader/lib/pkgconfig:$PKG_CONFIG_PATH"
          export PKG_CONFIG_PATH="/usr/local/opt/opencl-headers/share/pkgconfig:$PKG_CONFIG_PATH"
          export PKG_CONFIG_PATH="/usr/local/opt/opencl-clhpp-headers/share/pkgconfig:$PKG_CONFIG_PATH"
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compile Janus
        run: |
          make download-external-libs
          VERBOSE=1 make -j`sysctl -n hw.logicalcpu`
